version: "3.9"

services:
  database:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mdsoln
      POSTGRES_DB: donation
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - donor-network

  image-mongo:
    image: mongo:6
    container_name: image-mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - donor-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "8088:80"
    networks:
      - donor-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: donation-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/donation
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mdsoln
    depends_on:
      - database
      - image-mongo
    networks:
      - donor-network

networks:
  donor-network:

volumes:
  pgadmin-data:
    driver: local
  postgres-data:
    driver: local
  mongo-data:
    driver: local