spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/donation
    username: postgres
    password: mdsoln
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    defer-datasource-initialization: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
  sql:
    init:
      mode: never
  data:
    mongodb:
      uri: mongodb://localhost:27017/images