spring:
  datasource:
    url: jdbc:postgresql://database:5432/donation
    username: postgres
    password: mdsoln
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
  sql:
    init:
      mode: never
  data:
    mongodb:
      uri: mongodb://image-mongo:27017/images